abbrv_dict = {
              "abbrev.": "abbreviation (of)",
              "Abbrev.": "abbreviation(s)",
              "Abd.": "Aberdeen",
              "Aberd.": "Aberdeen",
              "Aberdeensh.": "Aberdeenshire",
              "abl.": "ablative",
              "Abol.": "abolition",
              "Aborig.": "aboriginal",
              "Abp.": "archbishop",
              "Abr.": "abridged",
              "Abridg.": "abridged",
              "Abridgem.": "abridgement",
              "absol.": "absolute(ly)",
              "Absol.": "absolute",
              "Abst.": "abstract(s)",
              "abstr.": "abstract",
              "Abstr.": "abstract(s)",
              "Acad.": "academia, academy, academic(al)",
              "acc.": "according (to)",
              "acc.": "accusative",
              "Acc.": "account(s)",
              "Accept.": "acceptance",
              "Accomm.": "accommodation",
              "Accompl.": "accomplished",
              "Accs.": "accounts",
              "Acct.": "account",
              "Accts.": "accounts",
              "accus.": "accusative",
              "Achievem.": "achievement",
              "A.D.": "Anno Domini",
              "ad.": "adaptation of",
              "Add.": "addendum, addenda",
              "Addit.": "addition(s)",
              "Addr.": "address",
              "adj.": "adjective, adjectival",
              "adj. phr.": "adjectival phrase",
              "adjs.": "adjectives",
              "Adm.": "admiral",
              "Adm.": "admiralty",
              "Admin.": "administration, administrative",
              "Admir.": "admiralty",
              "Admon.": "admonition",
              "Admonit.": "admonition",
              "adv.": "adverb, adverbial(ly)",
              "Adv.": "advanced",
              "Adv.": "advances",
              "Adv.": "adventure(s)",
              "Adv.": "advices",
              "Adv.": "advocate",
              "Advancem.": "advancement(s)",
              "advb.": "adverb, adverbial(ly)",
              "Advert.": "advertisement",
              "Advoc.": "advocate",
              "advs.": "adverbs",
              "Advt.": "advertisement",
              "Advts.": "advertisements",
              "Aerodynam.": "aerodynamics",
              "Aeronaut.": "aeronautics, aeronautical",
              "Aff.": "affairs",
              "Affect.": "affecting",
              "Affect.": "affection(s)",
              "Afr.": "Africa(n)",
              "Agric.": "agriculture, agricultural",
              "agst.": "against",
              "Alch.": "alchemy",
              "Alg.": "algebra",
              "Alleg.": "allegiance",
              "Allit.": "alliterative",
              "Alm.": "almanac",
              "Alph.": "alphabet, alphabetical",
              "alt.": "alteration",
              "Amer.": "America, American",
              "Anal.": "analysis",
              "Analyt.": "analytic(al)",
              "Anat.": "anatomy, anatomical",
              "Anc.": "ancient",
              "Anecd.": "anecdotes",
              "Ang.": "Anglian",
              "Angl.": "Anglian",
              "Anglo-Ind.": "Anglo-Indian",
              "Anim.": "animal(s)",
              "Ann.": "annal(s)",
              "Ann.": "annual",
              "Anniv.": "anniversary",
              "Annot.": "annotation",
              "Anon.": "(in author names) Anonymous",
              "Answ.": "answer",
              "Ant.": "antiquities",
              "Anthrop.": "anthropology",
              "Anthropol.": "anthropology, anthropological",
              "Antiq.": "antiquity, antiquities",
              "aphet.": "aphetic, aphetized",
              "Apoc.": "apocalyptic(al)",
              "Apol.": "apology, apologies",
              "app.": "apparently",
              "App.": "appendix",
              "Appl.": "applied",
              "Applic.": "application(s)",
              "appos.": "appositive(ly)",
              "Apr.": "April",
              "Arab.": "Arabic",
              "Arb.": "(in author names) Arber",
              "arch.": "archaic",
              "Arch.": "architecture",
              "Arch.": "archive(s)",
              "Archaeol.": "archaeology, archaeological",
              "Archipel.": "archipelago",
              "Archit.": "architecture, architectural",
              "Argt.": "argument",
              "Arith.": "arithmetic",
              "Arithm.": "arithmetic, arithmetical",
              "Arrangem.": "arrangement",
              "art.": "article",
              "Artic.": "articulation",
              "Artific.": "artificial",
              "Artill.": "artillery",
              "Ashm.": "(in author names) Ashmole",
              "Assemb.": "assembly, assemblies",
              "Assoc.": "association",
              "Assoc. Football": "Association Football",
              "Assyriol.": "Assyriology",
              "Astr.": "astronomy",
              "Astrol.": "astrology",
              "Astron.": "astronomy, astronomic(al)",
              "Astronaut.": "astronautics, astronautical",
              "Att.": "Attic",
              "attrib.": "attributive(ly)",
              "Attrib.": "attribute(s)",
              "Aug.": "August",
              "Austral.": "Australia(n)",
              "Auth.": "author(s)",
              "Autobiog.": "autobiography",
              "Autobiogr.": "autobiography, autobiographic(al)",
              "A.V.": "Authorized Version",
              "Ayrsh.": "Ayrshire",
              "": "",
              "Bacteriol.": "bacteriology, bacteriologic(al)",
              "B.C.": "Before Christ",
              "B.C.": "British Columbia",
              "Bedford.": "Bedfordshire",
              "Bedfordsh.": "Bedfordshire",
              "bef.": "before",
              "Bel & Dr.": "(in the Apocrypha) Bel and the Dragon",
              "Belg.": "Belgian",
              "Berks.": "Berkshire",
              "Berksh.": "Berkshire",
              "Berw.": "Berwickshire",
              "Berwicksh.": "Berwickshire",
              "betw.": "between",
              "Bibliogr.": "bibliography",
              "Biochem.": "biochemistry, biochemical",
              "Biog.": "biography",
              "Biogr.": "biography, biographic(al)",
              "Biol.": "biology, biological",
              "Bk.": "book",
              "Bks.": "books",
              "BNC": "British National Corpus",
              "Bord.": "border",
              "Bot.": "botany, botanic(al)",
              "Bp.": "Bishop",
              "Braz.": "Brazilian",
              "Brit.": "Britain, British",
              "Bucks.": "Buckinghamshire",
              "Build.": "building",
              "Bull.": "bulletin",
              "Bur.": "bureau",
              "c.": "century",
              "C.": "county, counties",
              "c": "(in dates) circa",
              "Cal.": "calendar",
              "Calc.": "calculus",
              "Calend.": "calendar",
              "Calif.": "California",
              "Calligr.": "calligraphy",
              "Camb.": "Cambridge",
              "Cambr.": "Cambridge",
              "Campanol.": "campanology",
              "Canad.": "Canadian",
              "Canterb.": "Canterbury",
              "Capt.": "captain",
              "Cartogr.": "cartography, cartographic(al)",
              "Catal.": "catalogue",
              "Catech.": "catechism",
              "Cath.": "Catholic",
              "cent.": "century",
              "Cent.": "central",
              "Cent.": "century",
              "Ceram.": "ceramics",
              "Cert.": "certificate",
              "Certif.": "certificate",
              "cf.": "confer, ‘compare’",
              "Ch.": "Church",
              "Chamb.": "chamber",
              "Char.": "character",
              "Charac.": "character",
              "Chas.": "Charles",
              "Chem. Engin.": "chemical engineering",
              "Chem.": "chemistry, chemical",
              "Chesh.": "Cheshire",
              "Ch. Hist.": "Church history",
              "Chr.": "Christian",
              "Chr.": "(in the Bible) Chronicles",
              "Chron.": "chronology, chronicle",
              "Chron.": "(in the Bible) Chronicles",
              "Chronol.": "chronology",
              "Chrons.": "chronicles",
              "Cinematogr.": "cinematography, cinematographic(al)",
              "Circ.": "circle",
              "Civ. Law": "civil law",
              "Civil Engin.": "civil engineering",
              "cl.": "clause",
              "Cl.": "club",
              "Class. Antiq.": "classical antiquities",
              "Class.": "classical",
              "Classif.": "classification",
              "Climatol.": "climatology",
              "Clin.": "clinical",
              "cogn. w.": "cognate with",
              "Col.": "colonel",
              "Col.": "(in the Bible) Colossians",
              "Coll.": "collected, collection",
              "Coll.": "college",
              "collect.": "collective(ly)",
              "Collect.": "collection",
              "colloq.": "colloquial(ly)",
              "Colloq.": "colloquies",
              "Coloss.": "(in the Bible) Colossians",
              "Com.": "common",
              "Com.": "commission",
              "Comb.": "combination(s)",
              "comb. form": "combining form",
              "Combs.": "combinations",
              "Comm.": "commerce, in commercial usage",
              "Comm.": "common",
              "Comm.": "commentary",
              "Comm.": "commission",
              "Comm.": "committee",
              "Commandm.": "commandment",
              "Commend.": "commendation",
              "Commerc.": "commercial",
              "Commiss.": "commission",
              "Comm. Law": "commercial law",
              "Commonw.": "commonwealth",
              "Communic.": "communication(s)",
              "comp.": "comparative",
              "comp.": "compound, composition",
              "Comp.": "companion",
              "Comp.": "company",
              "Compan.": "companion(s)",
              "Comp. Anat.": "comparative anatomy",
              "compar.": "comparative",
              "Compar.": "comparative",
              "Compend.": "compendium, compendious",
              "compl.": "complement",
              "Compl.": "complete",
              "Compos.": "composition",
              "conc.": "concerning",
              "Conc.": "concise",
              "Conch.": "conchology",
              "Concl.": "conclusion",
              "concr.": "concrete(ly)",
              "Conf.": "conference",
              "Conf.": "confession",
              "Confid.": "confidential",
              "Confl.": "conflict",
              "Confut.": "confutation",
              "Congr.": "congress",
              "Congreg.": "congregation",
              "Congress.": "congressional",
              "conj.": "conjugation",
              "conj.": "conjunction",
              "Conn.": "Connecticut",
              "cons.": "consonant",
              "Consc.": "conscience",
              "Consecr.": "consecrated, consecration",
              "Consid.": "consideration(s)",
              "Consol.": "consolation",
              "const.": "construction, construed with",
              "Constit. Hist.": "constitutional history",
              "Constit.": "constitution(al)",
              "Constr.": "construction",
              "Contemp.": "contemporary",
              "Contempl.": "contemplation",
              "contempt.": "contemptuous(ly)",
              "Contend.": "contending(s)",
              "Content.": "contention",
              "Contin.": "continuation",
              "contr.": "contracted, contraction",
              "contr.": "contrasted (with)",
              "Contradict.": "contradiction",
              "Contrib.": "contribution",
              "Controv.": "controversial",
              "Controv.": "controversy",
              "Conv.": "convention",
              "Convent.": "convention",
              "Conversat.": "conversation",
              "Convoc.": "convocation",
              "Cor.": "(in the Bible) Corinthians",
              "Cornw.": "Cornwall",
              "Coron.": "coronation",
              "Corr.": "correspondence",
              "corresp.": "corresponding (to)",
              "Corresp.": "correspondence",
              "Counc.": "council",
              "Courtsh.": "courtship",
              "cpd.": "compound",
              "Craniol.": "craniology",
              "Craniom.": "craniometry",
              "Crim.": "criminal",
              "Crim. Law": "criminal law",
              "Crit.": "critical",
              "Crit.": "criticism",
              "Crt.": "court",
              "Crts.": "courts",
              "Cryptogr.": "cryptography",
              "Crystallogr.": "crystallography",
              "Ct.": "count",
              "Ct.": "court",
              "Cumb.": "Cumberland",
              "Cumberld.": "Cumberland",
              "Cumbld.": "Cumberland",
              "Cycl.": "cyclopaedia",
              "Cytol.": "cytology, cytological",
              "Dan.": "(in the Bible) Daniel",
              "dat.": "dative",
              "Dau.": "daughter",
              "D.C.": "District of Columbia",
              "Deb.": "debate",
              "Dec.": "December",
              "Declar.": "declaration",
              "Ded.": "dedicated",
              "Ded.": "dedication",
              "def.": "definite",
              "def.": "definition",
              "Def.": "defence",
              "Deliv.": "deliverance",
              "dem.": "demonstrative",
              "Demonstr.": "demonstration",
              "Dep.": "department",
              "Dep.": "deputy",
              "Depred.": "depredation",
              "Depredat.": "depredation",
              "Dept.": "department",
              "Derbysh.": "Derbyshire",
              "deriv.": "derivative (in etymologies)",
              "derog.": "derogatory",
              "Descr.": "description, descriptive",
              "Deut.": "(in the Bible) Deuteronomy",
              "Devel.": "development",
              "Devonsh.": "Devonshire",
              "dial.": "dialect",
              "Dial.": "dialect",
              "Dict.": "dictionary",
              "Diffic.": "difficult, difficulty",
              "dim.": "diminutive",
              "Direct.": "direction",
              "Dis.": "disease(s)",
              "Disc.": "discourse",
              "Discipl.": "discipline",
              "Discov.": "discovery",
              "Discrim.": "discrimination",
              "Discuss.": "discussion",
              "Diss.": "dissertation",
              "Dist.": "district",
              "Distemp.": "distemper",
              "Distill.": "distilling",
              "Distrib.": "distribution",
              "Div.": "divinity",
              "Div.": "division",
              "Divers.": "diversity",
              "Dk.": "Duke",
              "Doc.": "document(s)",
              "Doctr.": "doctrine",
              "Domest.": "domestic",
              "Durh.": "Durham",
              "dyslog.": "dyslogistic",
              "e.": "east",
              "E.": "east, eastern",
              "E. Afr.": "East Africa(n)",
              "E. Angl.": "East Anglia(n)",
              "E. Anglian": "East Anglian",
              "East Ind.": "East Indies, East Indian",
              "east.": "eastern (dialect)",
              "Eccl.": "ecclesiastical",
              "Eccl.": "(in the Bible) Ecclesiastes",
              "Eccles.": "ecclesiastical",
              "Eccles.": "(in the Bible) Ecclesiastes",
              "Eccl. Hist.": "ecclesiastical history",
              "Eccl. Law": "ecclesiastical law",
              "Ecclus.": "(in the Apocrypha) Ecclesiasticus",
              "Ecol.": "ecology, ecological",
              "Econ.": "economics, economic(al)",
              "ed.": "edition",
              "Ed.": "edition",
              "Ed.": "Edward",
              "E.D.D.": "English Dialect Dictionary",
              "Edin.": "Edinburgh",
              "Edinb.": "Edinburgh",
              "Educ.": "education, education(al)",
              "Edw.": "Edward",
              "E.E.T.S.": "Early English Text Society",
              "Egypt.": "Egyptian",
              "Egyptol.": "Egyptology",
              "E. Ind.": "East Indies, East Indian",
              "Electr.": "electricity, electric(al)",
              "Electr. Engin.": "electrical engineering",
              "Electro-magn.": "electro-magnetism",
              "Electro-physiol.": "electro-physiology",
              "Elem.": "element(s), elementary",
              "Eliz.": "Elizabeth",
              "Elizab.": "Elizabethan",
              "ellipt.": "elliptical(ly)",
              "Emb.": "embassy",
              "Embryol.": "embryology, embryologic(al)",
              "e. midl.": "east midland (dialect)",
              "emph.": "emphatic(ally)",
              "Encycl.": "encyclopaedia, encyclopaedic",
              "Encycl. Brit.": "Encyclopaedia Britannica",
              "Encycl. Metrop.": "Encyclopaedia Metropolitana",
              "Eng.": "England, English",
              "Engin.": "engineering",
              "Englishw.": "Englishwomen",
              "Enq.": "enquiry",
              "Ent.": "entomology, entomological",
              "Enthus.": "enthusiasm",
              "Entom.": "entomology, entomological",
              "Entomol.": "entomology, entomological",
              "Enzymol.": "enzymology",
              "eOE": "(in dates) early Old English",
              "Ep.": "epistle",
              "Eph.": "(in the Bible) Ephesians",
              "Ephes.": "(in the Bible) Ephesians",
              "Epil.": "epilogue",
              "Episc.": "episcopacy",
              "Epist.": "epistle",
              "Epit.": "epitaph",
              "Equip.": "equipment",
              "erron.": "erroneous(ly)",
              "Esd.": "(in the Apocrypha) Esdras",
              "esp.": "especially",
              "Ess.": "essay(s)",
              "Essent.": "essential",
              "Establ.": "establishment",
              "Esth.": "(in the Bible) Esther",
              "Ethnol.": "ethnology",
              "etym.": "etymology",
              "etymol.": "etymological(ly)",
              "Etymol.": "etymology, etymological",
              "euphem.": "euphemistic(ally)",
              "Eval.": "evaluation",
              "Evang.": "evangelical",
              "Even.": "evening",
              "Evid.": "evidence",
              "Evol.": "evolution, evolutionary",
              "Ex. doc.": "executive document",
              "Exalt.": "exaltation",
              "Exam.": "examination",
              "exc.": "except",
              "Exch.": "exchange",
              "Exch.": "exchequer",
              "Exec.": "execution",
              "Exec.": "executive",
              "Exerc.": "exercise(s)",
              "Exhib.": "exhibition, exhibit(s)",
              "Exod.": "(in the Bible) Exodus",
              "Exped.": "expedition",
              "Exper.": "experiment, experimental",
              "Explan.": "explanation",
              "Explic.": "explication",
              "Explor.": "exploration",
              "Expos.": "exposition, expository",
              "Ezek.": "(in the Bible) Ezekiel",
              "f.": "feminine",
              "f.": "folio",
              "Fab.": "fable(s)",
              "fam.": "familiar(ly)",
              "Fam.": "family",
              "famil.": "familiar(ly)",
              "Farew.": "farewell",
              "Feb.": "February",
              "fem.": "feminine",
              "Ff.": "folios",
              "Fifesh.": "Fifeshire",
              "fig.": "figurative(ly)",
              "fl.": "floruit, ‘flourished’",
              "Footpr.": "footprint",
              "Forfarsh.": "Forfarshire",
              "Fortif.": "fortification",
              "Fortn.": "fortnightly",
              "Found.": "foundation(s)",
              "Fr.": "father",
              "Fr.": "French",
              "Fr.": "from",
              "Fragm.": "fragment(s)",
              "Fratern.": "fraternity",
              "freq.": "frequently",
              "Friendsh.": "friendship",
              "Fund.": "fundamental(s)",
              "Furnit.": "furniture",
              "fut.": "future",
              "Gal.": "(in the Bible) Galatians",
              "Gard.": "garden, gardening",
              "Gastron.": "gastronomy",
              "Gaz.": "gazette",
              "Gd.": "good",
              "gen.": "general(ly)",
              "gen.": "genitive",
              "Gen.": "general",
              "Gen.": "(in the Bible) Genesis",
              "Geo.": "George",
              "Geog.": "geography",
              "Geogr.": "geography, geographic(al)",
              "Geol.": "geology, geologic(al)",
              "Geom.": "geometry, geometric(al)",
              "Geomorphol.": "geomorphology",
              "Ger.": "German",
              "gerund.": "gerundial",
              "Glac.": "glacier(s)",
              "Glasg.": "Glasgow",
              "Glos.": "Gloucestershire",
              "Gloss.": "glossary",
              "Glouc.": "Gloucestershire",
              "Gloucestersh.": "Gloucestershire",
              "Gosp.": "gospel(s)",
              "Gov.": "government",
              "Govt.": "government",
              "Gr.": "grammar",
              "Gram.": "grammar",
              "Gramm. Analysis": "grammatical analysis",
              "Gt.": "great",
              "Gynaecol.": "gynaecology",
              "Hab.": "(in the Bible) Habakkuk",
              "Haematol.": "haematology",
              "Hag.": "(in the Bible) Haggai",
              "Hampsh.": "Hampshire",
              "Handbk.": "handbook",
              "Hants.": "Hampshire",
              "Heb.": "Hebrew",
              "Heb.": "(in the Bible) Hebrews",
              "Hebr.": "(in the Bible) Hebrews",
              "Hen.": "Henry",
              "Her.": "heraldry",
              "Herb.": "herbalism",
              "Heref.": "Herefordshire",
              "Hereford.": "Herefordshire",
              "Herefordsh.": "Herefordshire",
              "Hertfordsh.": "Hertfordshire",
              "Hierogl.": "Hieroglyphic",
              "hist.": "historical",
              "Hist.": "history, historic(al)",
              "Histol.": "histology, histologic(al)",
              "Hom.": "homilies",
              "Horol.": "horology",
              "Hort.": "horticulture, horticultural",
              "Hos.": "(in the Bible) Hosea",
              "Hosp.": "hospital",
              "Househ.": "household",
              "Housek.": "housekeeping",
              "Husb.": "husbandry",
              "Hydraul.": "hydraulic",
              "Hydrol.": "hydrology, hydrological",
              "Ichth.": "ichthyology",
              "Icthyol.": "icthyology",
              "Ideol.": "ideology, ideological",
              "Idol.": "idolatry",
              "Illustr.": "illustrated, illustration(s)",
              "Imag.": "imaginary, imagination",
              "imit.": "imitative",
              "Immunol.": "immunology",
              "imp.": "imperative",
              "imperf.": "imperfect",
              "impers.": "impersonal",
              "impf.": "imperfect",
              "Impr.": "impression(s)",
              "Impr.": "imprint",
              "Impr.": "improved",
              "improp.": "improper(ly)",
              "Inaug.": "inaugural",
              "Inclos.": "inclosure",
              "Ind.": "India(n)",
              "ind.": "indicative",
              "ind.": "indirect",
              "Ind.": "industry",
              "indef.": "indefinite",
              "indic.": "indicative",
              "indir.": "indirect",
              "Industr.": "industrial",
              "Industr. Rel.": "industrial relations",
              "infin.": "infinitive",
              "infl.": "influenced",
              "Infl.": "influence",
              "Innoc.": "innocence, innocent",
              "Inorg.": "inorganic",
              "Inq.": "inquiry",
              "Inst.": "institute, institution",
              "instr.": "instrumental",
              "Instr.": "instruction",
              "int.": "interjection",
              "Intell.": "intelligence, intelligent",
              "Intellect.": "intellectual",
              "Interc.": "intercourse",
              "interj.": "interjection",
              "Interl.": "interlude",
              "Internat.": "international",
              "Interpr.": "interpretation",
              "interrog.": "interrogative",
              "intr.": "intransitive",
              "intrans.": "intransitive",
              "Intro.": "introduction",
              "Introd.": "introduction, introductory",
              "Inv.": "inventory, inventories",
              "Invent.": "invention(s)",
              "Invent.": "inventory, inventories",
              "Invertebr.": "invertebrate, invertebrated",
              "Invert. Zool.": "invertebrate zoology",
              "Investig.": "investigation",
              "Investm.": "investment",
              "Invoc.": "invocation",
              "Ir.": "Irish",
              "Irel.": "Ireland",
              "iron.": "ironically",
              "irreg.": "irregular(ly)",
              "Isa.": "(in the Bible) Isaiah",
              "Ital.": "Italian",
              "Jahrb.": "Jahrbuch",
              "Jam.": "(in the Bible) James",
              "Jam.": "(in author names) Jamieson",
              "Jan.": "January",
              "Jap.": "Japanese",
              "Jas.": "James",
              "Jas.": "(in the Bible) James",
              "Jer.": "(in the Bible) Jeremiah",
              "joc.": "jocular(ly)",
              "Josh.": "(in the Bible) Joshua",
              "Jrnl.": "journal",
              "Jrnls.": "journals",
              "Jud.": "(in the Bible) Judges",
              "Judg.": "(in the Bible) Judges",
              "Jul.": "July",
              "Jun.": "June",
              "Jun.": "junior",
              "Jurisd.": "jurisdiction",
              "Jurisdict.": "jurisdiction",
              "Jurispr.": "jurisprudence",
              "Justif.": "justification",
              "Justific.": "justification",
              "K.": "king",
              "Kent.": "Kentish",
              "Kgs.": "(in the Bible) Kings",
              "King’s Bench Div.": "King’s Bench Division",
              "Kingd.": "kingdom",
              "Knowl.": "knowledge",
              "Kpr.": "keeper",
              "l.": "line",
              "Lab.": "laboratory",
              "Lam.": "(in the Bible) Lamentations",
              "Lament": "lamentation",
              "Lament.": "(in the Bible) Lamentations",
              "Lanc.": "Lancashire",
              "Lancash.": "Lancashire",
              "Lancs.": "Lancashire",
              "Lang.": "language",
              "Langs.": "languages",
              "Lat.": "Latin",
              "Ld.": "Lord",
              "Lds.": "Lords",
              "Lect.": "lecture(s)",
              "Leechd.": "leechdom",
              "Leg.": "legend(s)",
              "Leicest.": "Leicestershire",
              "Leicester.": "Leicestershire",
              "Leicestersh.": "Leicestershire",
              "Leics.": "Leicestershire",
              "Let.": "letter",
              "Lett.": "letters",
              "Lev.": "(in the Bible) Leviticus",
              "Lex.": "lexicon",
              "Libr.": "library",
              "Limnol.": "limnology",
              "Lincolnsh.": "Lincolnshire",
              "Lincs.": "Lincolnshire",
              "Ling.": "linguistic(s)",
              "Linn.": "Linnean",
              "lit.": "literal(ly)",
              "Lit.": "literary, literature",
              "Lithogr.": "lithography",
              "Lithol.": "lithology",
              "Liturg.": "liturgy",
              "ll.": "lines",
              "lOE": "(in dates) late Old English",
              "Lond.": "London",
              "LXX": "Septuagint",
              "m.": "masculine",
              "Macc.": "(in the Apocrypha) Maccabees",
              "Mach.": "machinery, machine(s)",
              "Mag.": "magazine",
              "Magn.": "magnetism, magnetic",
              "Mal.": "(in the Bible) Malachi",
              "Man.": "manual",
              "Managem.": "management",
              "Manch.": "Manchester",
              "Manip.": "manipulation",
              "Manuf.": "manufacturing, manufacture(s)",
              "Mar.": "March",
              "masc.": "masculine",
              "Mass.": "Massachussets",
              "Math.": "mathematics, mathematical",
              "Matt.": "(in the Bible) Matthew",
              "Meas.": "measure",
              "Measurem.": "measurement",
              "Mech.": "mechanics, mechanical",
              "med.": "medieval",
              "Med.": "medicine, medical",
              "Medit.": "meditation",
              "Mem.": "memoir(s)",
              "Merc.": "mercury",
              "Merch.": "merchant(s)",
              "Metall.": "metallurgy",
              "Metallif.": "metalliferous",
              "Metallogr.": "metallography, metallographic(al)",
              "Metallogr.": "metallography",
              "Metamorph.": "metamorphosis",
              "Metaph.": "metaphysics",
              "metaphor.": "metaphorical(ly)",
              "Meteorol.": "meteorology, meteorologic(al)",
              "Meth.": "method(s)",
              "metr. gr.": "metri gratia",
              "Metrop.": "metropolitan, metropolis",
              "Mex.": "Mexican",
              "Mic.": "(in the Bible) Micah",
              "Mich.": "Michigan",
              "Microbiol.": "microbiology",
              "Microsc.": "microscopic(al)",
              "midl.": "midland(s) (dialect)",
              "Mil.": "military",
              "Milit.": "military",
              "Min.": "mineralogy",
              "Mineral.": "mineralogy, minaralogic(al)",
              "Misc.": "miscellaneous, miscellany",
              "Miscell.": "miscellany",
              "mispr.": "misprinted",
              "mod.": "modern",
              "Mod.": "modern",
              "Monum.": "monument",
              "Morphol.": "morphology",
              "MS.": "manuscript",
              "MSS.": "manuscripts",
              "Mt.": "mount(ain)",
              "Mtg.": "meeting",
              "Mts.": "mountains",
              "Munic.": "municipal",
              "Munif.": "munificence",
              "Munim.": "muniment",
              "Mus.": "music, musical",
              "Mus.": "museum",
              "Myst.": "mystery",
              "Myth.": "mythology",
              "Mythol.": "mythology",
              "n.": "neuter",
              "n.": "north",
              "n.": "noun",
              "N.": "north, northern",
              "N. Afr.": "North Africa(n)",
              "Nah.": "(in the Bible) Nahum",
              "N. Amer.": "North America(n)",
              "Narr.": "narrative",
              "Narrat.": "narrative",
              "Nat.": "natural",
              "Nat. Hist.": "natural history",
              "Nat. Philos.": "natural philosophy",
              "Nat. Sci.": "natural science",
              "Naut.": "nautical",
              "Nav.": "naval",
              "Nav.": "navigation",
              "Navig.": "navigation",
              "N. Carolina": "North Carolina",
              "N. Dakota": "North Dakota",
              "n.e.": "north-eastern (dialect)",
              "N.E.": "north-east, north-eastern",
              "N.E.D.": "New English Dictionary",
              "Neh.": "(in the Bible) Nehemiah",
              "Neighb.": "neighbour(s), neighbourhood",
              "Nerv.": "nervous",
              "Neurol.": "neurology, neurologic(al)",
              "Neurosurg.": "neurosurgery",
              "New Hampsh.": "New Hampshire",
              "Newc.": "Newcastle",
              "Newspr.": "newsprint",
              "N. Ir.": "Northern Irish",
              "N. Irel.": "Northern Ireland",
              "No.": "number",
              "nom.": "nominative",
              "Non-conf.": "nonconformist(s)",
              "nonce-wd.": "nonce-word",
              "Nonconf.": "nonconformist(s)",
              "Norf.": "Norfolk",
              "north.": "northern (dialect)",
              "Northamptonsh.": "Northamptonshire",
              "Northants.": "Northamptonshire",
              "Northumb.": "Northumberland, Northumbrian",
              "Northumbld.": "Northumberland",
              "Northumbr.": "Northumbrian",
              "Norw.": "Norwegian",
              "Norweg.": "Norwegian",
              "Notts.": "Nottinghamshire",
              "Nov.": "November",
              "ns.": "nouns",
              "N.S. Wales": "New South Wales",
              "N.S.W.": "New South Wales",
              "N.T.": "New Testament",
              "Nucl.": "nuclear",
              "Num.": "(in the Bible) Numbers",
              "Numism.": "numismatics",
              "n.w.": "north-western (dialect)",
              "N.W.": "north-west, north-western",
              "N.Y.": "New York",
              "N.Z.": "New Zealand",
              "Obad.": "(in the Bible) Obadiah",
              "Obed.": "obedience",
              "obj.": "object, objective",
              "Obj.": "object(s)",
              "obl.": "oblique",
              "obs.": "obsolete",
              "Obs.": "obsolete",
              "Observ.": "observation(s)",
              "Obstet.": "obstetric(s)",
              "Obstetr.": "obstetric(s)",
              "Obstetr. Med.": "obstetric medicine",
              "occas.": "occasionally",
              "Occas.": "occasional",
              "Occup.": "occupation(al)",
              "Occurr.": "occurrence",
              "Oceanogr.": "oceanography, oceanographic(al)",
              "Oct.": "October",
              "OE": "(in dates) Old English",
              "O.E.D.": "Oxford English Dictionary",
              "Off.": "official, office",
              "Offic.": "official",
              "Okla.": "Oklahoma",
              "Ont.": "Ontario",
              "Ophthalm.": "ophthalmology",
              "Ophthalmol.": "ophthalmology, ophtalmologic(al)",
              "opp.": "opposed (to), the opposite (of)",
              "Oppress.": "oppression",
              "Opt.": "optics",
              "Orac.": "oracle(s)",
              "Ord.": "order(s)",
              "Ord.": "ordinance(s)",
              "Org.": "organic",
              "Organ. Chem.": "organic chemistry",
              "Org. Chem.": "organic chemistry",
              "orig.": "origin(al)(ly)",
              "Orig.": "original",
              "Orkn.": "Orkney",
              "Ornith.": "ornithology",
              "Ornithol.": "ornithology, ornithologic(al)",
              "Orthogr.": "orthography",
              "O.T.": "Old Testament",
              "Outl.": "outline",
              "Oxf.": "Oxford",
              "Oxfordsh.": "Oxfordshire",
              "Oxon.": "Oxfordshire",
              "p.": "page",
              "pa.": "past",
              "Pa.": "Pennsylvania",
              "Palaeobot.": "palaeobotany",
              "Palaeogr.": "palaeography",
              "Palaeont.": "palaeontology",
              "Palaeontol.": "palaeontology, palaeontologic(al)",
              "pa. pple.": "passive participle, past participle",
              "Paraphr.": "paraphrase, paraphrased",
              "Parasitol.": "parasitology",
              "Parl.": "parliament, parliamentary",
              "Parnass.": "Parnassus",
              "pass.": "passive(ly)",
              "pa. t.": "past tense",
              "Path.": "pathology, pathologic(al)",
              "Pathol.": "pathology, pathologic(al)",
              "Peculat.": "peculation(s)",
              "Penins.": "peninsula",
              "perf.": "perfect",
              "Perf.": "perfect, perfection",
              "perh.": "perhaps",
              "Periodontol.": "periodontology, periodontologic(al)",
              "pers.": "person(al)",
              "Pers.": "Persian",
              "Pers.": "personal",
              "Persec.": "persecution(s)",
              "personif.": "personified",
              "Perthsh.": "Perthshire",
              "Pet.": "(in the Bible) Peter",
              "Petrogr.": "petrography, petrographic(al)",
              "Petrol.": "petrology, petrologic(al)",
              "pf.": "perfect",
              "Pharm.": "pharmacology",
              "Pharmaceut.": "pharmaceutical",
              "Pharmacol.": "pharmacology, pharmacological",
              "Phil.": "philosophy, philosophic(al)",
              "Phil.": "(in the Bible) Philippians",
              "Philad.": "Philadelphia",
              "Philem.": "(in the Bible) Philemon",
              "Philipp.": "(in the Bible) Philippians",
              "Philol.": "philology, philologic(al)",
              "Philos.": "philosophy, philosophic(al)",
              "Phoen.": "Phoenician",
              "phonet.": "phonetic(ally)",
              "Phonol.": "phonology",
              "Photog.": "photography",
              "Photogr.": "photography, photographic(al)",
              "phr.": "phrase",
              "Phrenol.": "phrenology",
              "Phys.": "physiology",
              "Physical Chem.": "physical chemistry",
              "Physical Geogr.": "physical geography",
              "Physiogr.": "physiography",
              "Physiol.": "physiology, physiologic(al)",
              "Pict.": "pictorial",
              "Pict.": "picture(s)",
              "pl.": "plural",
              "plur.": "plural",
              "poet.": "poetic(al)",
              "Poet.": "poetical",
              "Pol.": "politics, political",
              "Pol. Econ.": "political economy",
              "Polit.": "politics, political",
              "Polytechn.": "polytechnic(al)",
              "pop.": "popular(ly)",
              "Pop.": "popular",
              "Porc.": "porcelain",
              "Port.": "Portuguese",
              "poss.": "possessive",
              "poss.": "possible, possibly",
              "Posth.": "posthumous(ly)",
              "Postm.": "postmaster",
              "Pott.": "pottery",
              "ppl.": "participial",
              "ppl. a.": "participial adjective",
              "ppl. adj.": "participial adjective",
              "ppl. adjs.": "participial adjectives",
              "pple.": "participle",
              "pples.": "participles",
              "P. R.": "public records",
              "pr.": "present",
              "Pract.": "practical",
              "Pract.": "practice",
              "prec.": "preceding",
              "pred.": "predicate",
              "predic.": "predicate, predicative(ly)",
              "Predict.": "prediction",
              "pref.": "prefix",
              "Pref.": "preface",
              "Preh.": "prehistoric",
              "Prehist.": "prehistory, prehistoric",
              "prep.": "preposition(al)",
              "Prerog.": "prerogative",
              "pres.": "present",
              "Pres.": "present",
              "Presb.": "Presbyterian",
              "Presb.": "presbytery",
              "Preserv.": "preservation",
              "pres. pple.": "present participle",
              "Prim.": "primer(s)",
              "Princ.": "principle(s)",
              "Print.": "printing",
              "priv.": "privative",
              "prob.": "probably",
              "Probab.": "probability, probabilities",
              "Probl.": "problem",
              "Proc.": "proceedings",
              "Prod.": "product(s)",
              "Prol.": "prologue",
              "pron.": "pronoun",
              "pron.": "pronunciation",
              "pronunc.": "pronunciation",
              "Pronunc.": "pronunciation",
              "prop.": "properly",
              "Prop.": "property, properties",
              "propr.": "proprietary",
              "Pros.": "prosody",
              "prov.": "proverb(ial)(ly)",
              "Prov.": "proverb",
              "Prov.": "(in the Bible) Proverbs",
              "Provid.": "providence(s)",
              "Provinc.": "provincial",
              "Provis.": "provisional",
              "pr. pple.": "present participle",
              "Ps.": "(in the Bible) Psalms",
              "pseudo-arch.": "pseudo-archaic",
              "pseudo-dial.": "pseudo-dialect",
              "pseudo-Sc.": "pseudo-Scots",
              "Psych.": "psychology",
              "Psychoanal.": "psychoanalysis",
              "Psychoanalyt.": "psychoanalytic",
              "Psychol.": "psychology, psychologic(al)",
              "Psychopathol.": "psychopathology, psychopathologic(al)",
              "Pt.": "part",
              "Publ.": "public",
              "Publ.": "publication",
              "Purg.": "purgatory",
              "Q.": "quarterly",
              "Q.": "queen",
              "Q. Eliz.": "Queen Elizabeth",
              "Qld.": "Queensland",
              "Quantum Mech.": "quantum mechanics",
              "Queen’s Bench Div.": "Queen’s Bench Division",
              "quot.": "quotation",
              "quots.": "quotations",
              "q.v.": "quod vide, ‘which see’",
              "R.": "royal",
              "Radiol.": "radiology",
              "R.A.F.": "Royal Air Force",
              "R.C.": "Roman Catholic(ism)",
              "R.C. Church": "Roman Catholic Church",
              "Reas.": "reason(s)",
              "Reb.": "rebellion",
              "Rebell.": "rebellion",
              "Rec.": "record(s)",
              "Reclam.": "reclamation",
              "Recoll.": "recollection",
              "Redempt.": "redemption",
              "redupl.": "reduplicating",
              "Ref.": "reference",
              "Ref.": "reformation",
              "refash.": "refashioned, refashioning",
              "refl.": "reflexive",
              "Refl.": "reflection(s)",
              "Refus.": "refusal",
              "Refut.": "refutation",
              "reg.": "regular",
              "Reg.": "register",
              "Regic.": "regicide",
              "Regist.": "register",
              "Regr.": "register",
              "rel.": "related",
              "rel.": "relative",
              "Rel.": "relating",
              "Relig.": "religion, religious",
              "Reminisc.": "reminiscence(s)",
              "Remonstr.": "remonstrance",
              "Renfrewsh.": "Renfrewshire",
              "Rep.": "report",
              "repr.": "representative, representing",
              "Reprod.": "reproduction, reproductive",
              "Rept.": "report",
              "Repub.": "republic",
              "Res.": "research",
              "Resid.": "residence, residential",
              "Ret.": "return",
              "Retrosp.": "retrospective",
              "Rev.": "review",
              "Rev.": "revised",
              "Rev.": "(in the Bible) Revelation",
              "Revol.": "revolution",
              "Rhet.": "rhetoric",
              "rhet.": "rhetorical(ly)",
              "Rhode Isl.": "Rhode Island",
              "Rich.": "Richard",
              "R.N.": "Royal Navy",
              "Rom.": "Roman",
              "Rom.": "(in the Bible) Romans",
              "Rom. Antiq.": "Roman antiquities",
              "Ross-sh.": "Ross-shire",
              "Roxb.": "Roxburgh",
              "Roy.": "royal",
              "Rudim.": "rudiment(s)",
              "Russ.": "Russia, Russian",
              "s.": "south",
              "S.": "south, southern",
              "S. Afr.": "South Africa(n)",
              "Sam.": "(in the Bible) Samuel",
              "Sask.": "Saskatchewan",
              "Sat.": "Saturday",
              "Sax.": "Saxon",
              "sc.": "scilicet, ‘understand’ or ‘supply’",
              "Sc.": "Scottish, Scots",
              "Scand.": "Scandinavia, Scandinavian",
              "S. Carolina": "South Carolina",
              "Sch.": "school",
              "Sci.": "science(s), scientific",
              "Scot.": "Scottish",
              "Scotl.": "Scotland",
              "Script.": "scripture",
              "Sculpt.": "sculpture",
              "S. Dakota": "South Dakota",
              "s.e.": "south-eastern (dialect)",
              "S.E.": "south-east, south-eastern",
              "Seismol.": "seismology",
              "Sel.": "selected",
              "Sel. comm.": "select committee",
              "Select.": "selection",
              "Sept.": "September",
              "Ser.": "series",
              "Serm.": "sermon(s)",
              "Sess.": "session",
              "Settlem.": "settlement",
              "Sev.": "several",
              "Shakes.": "Shakespeare",
              "Shaks.": "Shakespeare",
              "Sheph.": "shepherd",
              "Shetl.": "Shetland",
              "Shropsh.": "Shropshire",
              "sing.": "singular",
              "Soc.": "society",
              "Sociol.": "sociology, sociological",
              "Som.": "Somerset",
              "Song of Sol.": "(in the Bible) Song of Solomon",
              "Song Sol.": "(in the Bible) Song of Solomon",
              "Sonn.": "sonnet",
              "south.": "southern (dialect)",
              "sp.": "spelling",
              "Span.": "Spanish",
              "spec.": "specifically",
              "Spec.": "special",
              "Spec.": "specimen(s)",
              "Specif.": "specification(s)",
              "Specim.": "specimen(s)",
              "Spectrosc.": "spectroscopy",
              "SS.": "saints",
              "St.": "Saint",
              "St.": "street",
              "Staff.": "Staffordshire",
              "Stafford.": "Staffordshire",
              "Staffordsh.": "Staffordshire",
              "Staffs.": "Staffordshire",
              "Stand.": "standard",
              "Stat.": "statistical",
              "Statist.": "statistical",
              "Stock Exch.": "stock exchange",
              "str.": "strong",
              "Stratigr.": "stratigraphy, stratigraphical",
              "Struct.": "structure, structural",
              "S.T.S.": "Scottish Text Society",
              "Stud.": "studies",
              "subj.": "subject",
              "subj.": "subjunctive",
              "Subj.": "subject(s)",
              "subjunct.": "subjunctive",
              "subord.": "subordinate",
              "subord. cl.": "subordinate clause",
              "Subscr.": "subscription",
              "Subscript.": "subscription",
              "subseq.": "subsequent(ly)",
              "subst.": "substantive(ly)",
              "suff.": "suffix",
              "Suff.": "Suffolk",
              "superl.": "superlative",
              "Suppl.": "supplement, supplementary",
              "Supplic.": "supplication(s)",
              "Suppress.": "suppression",
              "Surg.": "surgery, surgical",
              "Surv.": "survey, surveying",
              "Sus.": "(in the Apocrypha) Susanna",
              "s.v.": "sub verbo, ‘under the word’",
              "s.w.": "south-western (dialect)",
              "S.W.": "south-west, south-western",
              "syll.": "syllable",
              "Symmetr.": "symmetrical",
              "Symp.": "symposium",
              "Syst.": "system",
              "t.": "tense",
              "Taxon.": "taxonomy, taxonomic",
              "techn.": "technical",
              "Techn.": "technical",
              "Technol.": "technology, technological",
              "Tel.": "telegraph",
              "Telecomm.": "telecommunications",
              "Telegr.": "telegraph",
              "Telegr.": "telegraphy, telegraphic(al)",
              "Teleph.": "telephony, telephonic",
              "Teratol.": "teratology",
              "Terminol.": "terminology, terminological",
              "Terrestr.": "terrestrial",
              "Test.": "testament",
              "Textbk.": "textbook",
              "Theat.": "theatre, theatrical",
              "Theatr.": "theatre, theatrical",
              "Theol.": "theology, theological",
              "Theoret.": "theoretical",
              "Thermonucl.": "thermonuclear",
              "Thes.": "thesaurus",
              "Thess.": "(in the Bible) Thessalonians",
              "Tim.": "(in the Bible) Timothy",
              "Tit.": "(in the Bible) Titus",
              "Topogr.": "topography, topographic(al)",
              "tr.": "translation, translating",
              "Trad.": "tradition, traditional",
              "Trag.": "tragedy",
              "trans.": "transitive",
              "Trans.": "transaction(s)",
              "transf.": "transferred sense",
              "transl.": "translation, translating",
              "Transl.": "translation",
              "Transubstant.": "transubstantiation",
              "Trav.": "travel(s)",
              "Treas.": "treasurer, treasury",
              "Treat.": "treatise",
              "Treatm.": "treatment",
              "Trib.": "tribune",
              "Trig.": "trigonometry",
              "Trigonom.": "trigonometry",
              "Trop.": "tropical",
              "Troub.": "troublesome",
              "Troubl.": "troublesome",
              "Typog.": "typography",
              "Typogr.": "typography",
              "U.K.": "United Kingdom",
              "ult.": "ultimately",
              "Univ.": "university",
              "unkn.": "unknown",
              "Unnat.": "unnatural",
              "Unoffic.": "unofficial",
              "unstr.": "unstressed",
              "Urin.": "urinary",
              "U.S.": "United States",
              "U.S.A.F.": "United States Air Force",
              "U.S.S.R.": "Union of Soviet Socialist Republics",
              "usu.": "usually",
              "Utilit.": "utilitarian",
              "v.": "verb",
              "Va.": "Virginia",
              "Vac.": "vacation",
              "Valedict.": "valediction",
              "var.": "variant",
              "varr.": "variants",
              "vars.": "variants",
              "vb.": "verb",
              "vbl.": "verbal",
              "vbl.n.": "verbal noun",
              "vbl. ns.": "verbal nouns",
              "vbs.": "verbs",
              "Veg.": "vegetable",
              "Veg. Phys.": "vegetable physiology",
              "Veg. Physiol.": "vegetable physiology",
              "Venet.": "Venetian",
              "Vertebr.": "vertebrate",
              "Vet.": "veterinary, veterinary science",
              "Vet. Med.": "veterinary medicine",
              "Vet. Path.": "veterinary pathology",
              "Vet. Sci.": "veterinary science",
              "Vet. Surg.": "veterinary surgery",
              "Vic.": "Victoria",
              "Vict.": "Victoria",
              "Vind.": "vindication, vindicated",
              "Vindic.": "vindication, vindicated",
              "Virg.": "virgin(s)",
              "Virol.": "virology",
              "viz.": "videlicet, ‘namely’",
              "Voc.": "vocabulary",
              "Vocab.": "vocabulary",
              "Vol.": "volume",
              "Vols.": "volumes",
              "Voy.": "voyage(s)",
              "vulg.": "vulgar(ly)",
              "Vulg.": "vulgar",
              "Vulg.": "Vulgate",
              "w.": "west",
              "W.": "west, western",
              "W. Afr.": "West Africa(n)",
              "Warwicksh.": "Warwickshire",
              "wd.": "word",
              "Wd.": "word",
              "west.": "western",
              "Westm.": "Westminster",
              "Westmld.": "Westmoreland",
              "Westmorld.": "Westmoreland",
              "Westmrld.": "Westmoreland",
              "Will.": "William",
              "Wilts.": "Wiltshire",
              "Wiltsh.": "Wiltshire",
              "W. Ind.": "West Indies, West Indian",
              "W. Indies": "West Indies",
              "Wis.": "Wisconsin",
              "Wisd.": "wisdom",
              "Wisd.": "(in the Apocrypha) Wisdom of Solomon",
              "wk.": "weak",
              "Wk.": "week",
              "Wk.": "work",
              "Wkly.": "weekly",
              "Wks.": "works",
              "Wonderf.": "wonderful",
              "Worc.": "Worcestershire",
              "Worcestersh.": "Worcestershire",
              "Worcs.": "Worcestershire",
              "Writ.": "writing(s)",
              "W. Va.": "West Virginia",
              "Yearbk.": "yearbook",
              "Yng.": "young",
              "Yorks.": "Yorkshire",
              "Yorksh.": "Yorkshire",
              "Yr.": "year",
              "Yrs.": "years",
              "Zech.": "(in the Bible) Zechariah",
              "Zeitschr.": "Zeitschrift",
              "Zeph.": "(in the Bible) Zephaniah",
              "Zoogeogr.": "zoogeography",
              "Zool.": "zoology, zoological",
               }

for ab in abbrv_dict:
    if "," in ab:
        abbrv_dict[ab] = abbrv_dict[ab][:abbrv_dict[ab].find(',')]
