# -*- coding: utf-8 -*-
"""
Created on Tue Aug 30 15:39:00 2016

@author: emmaflint
"""

abbrev_dict = {
               "Abbrev.": "abbreviation",
               "Abr.": "abridged",
               "Abridg.": "abridged",
               "Absol.": "absolute",
               "Abst.": "abstract",
               "abstr.": "abstract",
               "Abstr.": "abstract",
               "acc.": "according ",
               "Acc.": "account",
               "Accomm.": "accommodation",
               "Accompl.": "accomplished",
               "Acct.": "account",
               "Accts.": "accounts",
               "Addr.": "address",
               "adj.": "adjective",
               "adjs.": "adjectives",
               "Adm.": "admiral",
               "adv.": "adverb",
               "advb.": "adverb",
               "Advert.": "advertisement",
               "Advt.": "advertisement",
               "Advts.": "advertisements",
               "Aff.": "affairs",
               "Afr.": "Africa",
               "agst.": "against",
               "Alg.": "algebra",
               "alt.": "alteration",
               "Ann.": "annual",
               "Anniv.": "anniversary",
               "anon.": "anonymous",
               "Anon.": "Anonymous",
               "Answ.": "answer",
               "Apol.": "apology",
               "Apr.": "April",
               "Arch.": "architecture",
               "Argt.": "argument",
               "Arith.": "arithmetic",
               "Artific.": "artificial",
               "Assemb.": "assembly",
               "Assoc.": "association",
               "Astr.": "astronomy",
               "Attrib.": "attribute",
               "Aug.": "August",
               "bef.": "before",
               "Belg.": "Belgian",
               "betw.": "between",
               "Biog.": "biography",
               "Bk.": "book",
               "Bks.": "books",
               "Braz.": "Brazilian",
               "c.": "century",
               "c": "circa",
               "Cal.": "calendar",
               "Calc.": "calculus",
               "Calif.": "California",
               "Camb.": "Cambridge",
               "Capt.": "captain",
               "Cath.": "Catholic",
               "cent.": "century",
               "Cent.": "century",
               "Cert.": "certificate",
               "Certif.": "certificate",
               "Char.": "character",
               "Circ.": "circle",
               "cl.": "clause",
               "Col.": "colonel",
               "Coll.": "college",
               "colloq.": "colloquial",
               "Comb.": "combination",
               "Combs.": "combinations",
               "Comm.": "commerce",
               "Comm.": "committee",
               "Commerc.": "commercial",
               "Commonw.": "commonwealth",
               "comp.": "comparative",
               "Comp.": "company",
               "conc.": "concerning",
               "Concl.": "conclusion",
               "Conf.": "conference",
               "Congr.": "congress",
               "conj.": "conjunction",
               "Conn.": "Connecticut",
               "cons.": "consonant",
               "Constr.": "construction",
               "Contemp.": "contemporary",
               "Cont.": "continuation",
               "Contrib.": "contribution",
               "Conv.": "convention",
               "Counc.": "council",
               "cpd.": "compound",
               "Crim.": "criminal",
               "Crit.": "critical",
               "Crit.": "criticism",
               "Crt.": "court",
               "Crts.": "courts",
               "Ct.": "count",
               "Ct.": "court",
               "Dec.": "December",
               "def.": "definite",
               "def.": "definition",
               "Dep.": "department",
               "Dep.": "deputy",
               "Dept.": "department",
               "Devel.": "development",
               "Dict.": "dictionary",
               "Dist.": "district",
               "Distrib.": "distribution",
               "Dk.": "Duke",
               "Docs.": "documents",
               "Doc.": "document",
               "e.": "east",
               "eds.": "editions",
               "ed.": "edition",
               "Ed.": "edition",
               "Ed.": "Edward",
               "Edw.": "Edward",
               "Emb.": "embassy",
               "Encycl.": "encyclopaedia",
               "Enq.": "enquiry",
               "Equip.": "equipment",
               "esp.": "especially",
               "Eval.": "evaluation",
               "Evid.": "evidence",
               "Exam.": "examination",
               "exc.": "except",
               "Exch.": "exchange",
               "Exerc.": "exercise",
               "f.": "feminine",
               "fam.": "familiar",
               "Fam.": "family",
               "Feb.": "February",
               "fem.": "feminine",
               "figs.": "figures",
               "fig.": "figure",
               "freq.": "frequently",
               "Gd.": "good",
               "gen.": "general",
               "Gen.": "general",
               "Geog.": "geography",
               "Gloss.": "glossary",
               "Gov.": "government",
               "Govt.": "government",
               "Gr.": "grammar",
               "Gt.": "great",
               "Handbk.": "handbook",
               "hist.": "historical",
               "Hosp.": "hospital",
               "Husb.": "husband",
               "Ind.": "industry",
               "indef.": "indefinite",
               "Inq.": "inquiry",
               "Intro.": "introduction",
               "Inv.": "inventory",
               "Investig.": "investigation",
               "Investm.": "investment",
               "Irel.": "Ireland",
               "irreg.": "irregular",
               "Jan.": "January",
               "Jrnl.": "journal",
               "Jrnls.": "journals",
               "Jul.": "July",
               "Jun.": "June",
               "Jun.": "junior",
               "K.": "king",
               "Kingd.": "kingdom",
               "Knowl.": "knowledge",
               "Lab.": "laboratory",
               "Lang.": "language",
               "Langs.": "languages",
               "Lat.": "Latin",
               "Ld.": "Lord",
               "Lds.": "Lords",
               "Lect.": "lecture",
               "Let.": "letter",
               "Letts.": "letters",
               "Libr.": "library",
               "Ling.": "linguistic",
               "m.": "masculine",
               "Mag.": "magazine",
               "Man.": "manual",
               "Mar.": "March",
               "masc.": "masculine",
               "Mass.": "Massachussets",
               "Meas.": "measure",
               "med.": "medieval",
               "Mem.": "memoir",
               "Merch.": "merchandise",
               "Meth.": "method",
               "Mich.": "Michigan",
               "Mil.": "military",
               "Milit.": "military",
               "mispr.": "misprinted",
               "mod.": "modern",
               "Mod.": "modern",
               "MS.": "manuscript",
               "Mtg.": "meeting",
               "Mts.": "mountains",
               "Mus.": "museum",
               "Myst.": "mystery",
               "Myth.": "mythology",
               "n.": "north",
               "n.": "noun",
               "Narr.": "narrative",
               "Nat.": "natural",
               "Naut.": "nautical",
               "Nav.": "naval",
               "Navig.": "navigation",
               "n.e.": "north-east, north-eastern",
               "Neurol.": "neurology",
               "No.": "number",
               "Norweg.": "Norwegian",
               "Nov.": "November",
               "Num.": "Numbers",
               "N.Z.": "New Zealand",
               "Observ.": "observation",
               "occas.": "occasionally",
               "Occas.": "occasional",
               "Occurr.": "occurrence",
               "Oct.": "October",
               "O.E.D.": "Oxford English Dictionary",
               "Offic.": "official",
               "Okla.": "Oklahoma",
               "Org.": "organic",
               "Orig.": "original",
               "Oxf.": "Oxford",
               "p.": "page",
               "pass.": "passive",
               "perf.": "perfect",
               "Pers.": "personal",
               "Photog.": "photography",
               "Photogr.": "photography",
               "phr.": "phrase",
               "Pict.": "pictorial",
               "Pict.": "picture",
               "pl.": "plural",
               "plur.": "plural",
               "pop.": "popular",
               "Pop.": "popular",
               "ppl.": "people",
               "pr.": "present",
               "Pract.": "practical",
               "Pract.": "practice",
               "prec.": "preceding",
               "pred.": "prediction",
               "pref.": "prefix",
               "pres.": "present",
               "Pres.": "present",
               "prob.": "probably",
               "Probl.": "problem",
               "Prod.": "product",
               "pron.": "pronoun",
               "pronunc.": "pronunciation",
               "Pronunc.": "pronunciation",
               "prop.": "properly",
               "Prov.": "proverb",
               "Provid.": "providence",
               "Provinc.": "provincial",
               "Psych.": "psychology",
               "Pt.": "part",
               "Publ.": "public",
               "Publ.": "publication",
               "Q.": "quarterly",
               "Q.": "queen",
               "quot.": "quotation",
               "quots.": "quotations",
               "R.A.F.": "Royal Air Force",
               "R.C.": "Roman Catholic",
               "Ref.": "reference",
               "reg.": "regular",
               "Reg.": "register",
               "Regist.": "register",
               "rel.": "relative",
               "Rep.": "report",
               "Rept.": "report",
               "Repub.": "republic",
               "Ret.": "return",
               "Rev.": "review",
               "Rev.": "revised",
               "Revol.": "revolution",
               "Rich.": "Richard",
               "R.N.": "Royal Navy",
               "Rom.": "Roman",
               "s.": "south",
               "Sat.": "Saturday",
               "Sax.": "Saxon",
               "Sch.": "school",
               "Scot.": "Scottish",
               "Scotl.": "Scotland",
               "Sept.": "September",
               "Sess.": "session",
               "Settlem.": "settlement",
               "Sev.": "several",
               "Soc.": "society",
               "sp.": "spelling",
               "Span.": "Spanish",
               "Spec.": "specimen",
               "St.": "Saint",
               "St.": "street",
               "std.": "standard",
               "Stand.": "standard",
               "str.": "strong",
               "subj.": "subject",
               "Subj.": "subject",
               "subord.": "subordinate",
               "syll.": "syllable",
               "Symmetr.": "symmetrical",
               "Syst.": "system",
               "techn.": "technical",
               "Techn.": "technical",
               "Telecomm.": "telecommunications",
               "Teleph.": "telephony, telephonic",
               "Test.": "testament",
               "Textbk.": "textbook",
               "Theol.": "theology, theological",
               "Thes.": "thesaurus",
               "Trag.": "tragedy",
               "transf.": "transfer",
               "Transl.": "translation",
               "Treatm.": "treatment",
               "Trig.": "trigonometry",
               "Trop.": "tropical",
               "Typogr.": "typography",
               "U.K.": "United Kingdom",
               "Univ.": "university",
               "unkn.": "unknown",
               "Unoffic.": "unofficial",
               "U.S.": "United States",
               "U.S.S.R.": "Union of Soviet Socialist Republics",
               "Vac.": "vacation",
               "var.": "variant",
               "vb.": "verb",
               "vbl.": "verbal",
               "vbs.": "verbs",
               "Veg.": "vegetable",
               "Vic.": "Victoria",
               "Vict.": "Victoria",
               "Vocab.": "vocabulary",
               "Vol.": "volume",
               "Vols.": "volumes",
               "w.": "west",
               "wd.": "word",
               "Wd.": "word",
               "Wis.": "Wisconsin",
               "wk.": "weak",
               "Wk.": "week",
               "Wk.": "work",
               "Wkly.": "weekly",
               "Wks.": "works",
               "Yearbk.": "yearbook",
               "Yng.": "young",
               "Yr.": "year",
               "Yrs.": "years",
               }
               
ambig_abbrevs = {
                 "Acad.": ["academia", "academy", "academic"],
                 "Admin.": ["administration", "administrative"],
                 "Adv.": ["advanced", "adventure"],
                 "Agric.": ["agriculture", "agricultural"],
                 "Amer.": ["America", "American"],
                 "art.": ["article", "artifact"],
                 "Biochem.": ["biochemistry", "biochemical"],
                 "Chem.": ["chemistry", "chemical"],
                 "Chron.": ["chronology", "chronicle"],
                 "corresp.": ["corresponding", "correspondence"],
                 "Descr.": ["description", "descriptive"],
                 "E.": ["east", "eastern"],
                 "Ecol.": ["ecology", "ecological"],
                 "Econ.": ["economics", "economical"],
                 "Educ.": ["education", "educational"],
                 "Electr.": ["electricity", "electrical"],
                 "Eng.": ["England", "English"],
                 "Fr.": ["French", "France"],
                 "Geogr.": ["geography", "geographical"],
                 "Geol.": ["geology", "geological"],
                 "Geom.": ["geometry", "geometrical"],
                 "Ger.": ["German", "Germany"],
                 "Hist.": ["history", "historical"],
                 "Illustr.": ["illustrated", "illustration"],
                 "Ind.": ["India", "Indian"],
                 "Industr.": ["industrial", "industry"],
                 "Inst.": ["institute", "institution"],
                 "Intell.": ["intelligence", "intelligent"],
                 "Introd.": ["introduction", "introductory"],
                 "Ital.": ["Italian", "Italy"],
                 "Jap.": ["Japanese", "Japan"],
                 "lit.": ["literal", "literally"],
                 "Lit.": ["literary", "literature"],
                 "Mach.": ["machinery", "machine"],
                 "Math.": ["mathematics", "mathematical"],
                 "Mech.": ["mechanics", "mechanical"],
                 "Med.": ["medicine", "medical"],
                 "Mex.": ["Mexican", "Mexico"],
                 "Misc.": ["miscellaneous", "miscellany"],
                 "Mt.": ["mount", "mountain"],
                 "Mus.": ["music", "musical"],
                 "N.": ["north", "northern"],
                 "N.E.": ["north-east", "north-eastern"],
                 "N.W.": ["north-west", "north-western"],
                 "obj.": ["object", "objective"],
                 "Occup.": ["occupation", "occupational"],
                 "Off.": ["official", "office"],
                 "opp.": ["opposed", "opposite"],
                 "orig.": ["origin", "original"],
                 "Parl.": ["parliament", "parliamentary"],
                 "Perf.": ["perfect", "perfection"],
                 "Phil.": ["philosophy", "philosophical"],
                 "Phys.": ["physiology", "physics"],
                 "Physiol.": ["physiology", "physiological"],
                 "Pol.": ["politics", "political"],
                 "Polit.": ["politics", "political"],
                 "Port.": ["Portuguese", "Portugal"],
                 "poss.": ["possible", "possibly"],
                 "Princ.": ["principle", "principality"],
                 "Probab.": ["probability", "probably"],
                 "Prop.": ["property", "proper"],
                 "Psychol.": ["psychology", "psychological"],
                 "Rec.": ["record", "recording"],
                 "repr.": ["representative", "representing"],
                 "Resid.": ["residence", "residential"],
                 "Russ.": ["Russia", "Russian"],
                 "S.": ["south", "southern"],
                 "Scand.": ["Scandinavia", "Scandinavian],
                 "Sci.": ["science", "scientific"],
                 "s.e.": ["south-east", "south-eastern"],
                 "S.E.": ["south-east", "south-eastern"],
                 "Sociol.": ["sociology", "sociological"],
                 "Struct.": ["structure", "structural"],
                 "Suppl.": ["supplement", "supplementary"],
                 "Surg.": ["surgery", "surgical"],
                 "Surv.": ["survey", "surveying"],
                 "s.w.": ["south-west", "south-western"],
                 "S.W.": ["south-west", "south-western"],
                 "Technol.": ["technology", "technological"],
                 "Tel.": ["telegraph", "telephone"],
                 "tr.": ["translation", "translating"],
                 "Trad.": ["tradition", "traditional"],
                 "transl.": ["translation", "translating"],
                 "Treas.": ["treasurer", "treasury"],
                 "W.": ["west", "western"],
                 }